(() => {
  'use strict';

  const copy = {
    en: { eyebrow: 'A small library to begin with', title: 'Start with a deck.<br><em>Make it yours.</em>', lede: 'Explore curated decks for languages, music, mathematics, programming and science. They are useful starting points — but the real magic is making a deck for exactly what you want to remember.', aiEyebrow: 'The better starting point', aiTitle: 'Your material is the <em>real deck.</em>', aiText: 'JustFlip includes AI-assisted workflows for turning notes, articles, books, lectures and ideas into importable flashcards. Start with a curated deck when it helps. Then make one that belongs to you.', aiCta: 'Create your own deck', libraryEyebrow: 'Curated collection', libraryTitle: 'Something worth<br><em>remembering.</em>', libraryText: 'Download a deck, open it in JustFlip, and begin reviewing. Every deck is available in the app\'s supported languages.', all: 'All decks', languages: 'Languages', music: 'Music', mathematics: 'Mathematics', programming: 'Programming', science: 'Science', download: 'Download deck', cards: 'cards', pack: 'pack', packs: 'packs', finalEyebrow: 'Bring your own curiosity', finalTitle: 'The best deck is the one<br><em>you need today.</em>', finalText: 'Start with a curated deck, import from Anki, or create something completely your own with AI-assisted workflows and JustFlip\'s calm review engine.', appStore: 'Download on the App Store' },
    cs: { eyebrow: 'Malá knihovna na začátek', title: 'Začni balíčkem.<br><em>Udělej ho svým.</em>', lede: 'Prozkoumej vybrané balíčky z jazyků, hudby, matematiky, programování a vědy. Jsou dobrým začátkem — ale skutečné kouzlo je vytvořit si balíček přesně pro to, co si chceš zapamatovat.', aiEyebrow: 'Lepší začátek', aiTitle: 'Tvoje materiály jsou <em>ten pravý balíček.</em>', aiText: 'JustFlip obsahuje AI nástroje, které promění poznámky, články, knihy, přednášky a nápady v kartičky připravené k importu. Začni vybraným balíčkem, když se to hodí. Pak si vytvoř vlastní.', aiCta: 'Vytvořit vlastní balíček', libraryEyebrow: 'Vybraná kolekce', libraryTitle: 'Něco, co stojí za to<br><em>si zapamatovat.</em>', libraryText: 'Stáhni si balíček, otevři ho v JustFlip a začni s opakováním. Každý balíček je dostupný v podporovaných jazycích aplikace.', all: 'Všechny balíčky', languages: 'Jazyky', music: 'Hudba', mathematics: 'Matematika', programming: 'Programování', science: 'Věda', download: 'Stáhnout balíček', cards: 'karet', pack: 'balíček', packs: 'balíčky', finalEyebrow: 'Přines si vlastní zvědavost', finalTitle: 'Nejlepší balíček je ten,<br><em>který dnes potřebuješ.</em>', finalText: 'Začni vybraným balíčkem, importuj z Anki nebo si s pomocí AI vytvoř úplně vlastní — s klidným opakováním JustFlip.', appStore: 'Stáhnout z App Store' },
    de: { eyebrow: 'Eine kleine Bibliothek für den Anfang', title: 'Beginne mit einem Deck.<br><em>Mach es zu deinem.</em>', lede: 'Entdecke kuratierte Decks für Sprachen, Musik, Mathematik, Programmierung und Naturwissenschaften. Sie sind ein guter Ausgangspunkt — die eigentliche Stärke liegt aber darin, ein Deck genau für das zu erstellen, was du behalten möchtest.', aiEyebrow: 'Der bessere Ausgangspunkt', aiTitle: 'Dein Material ist das <em>eigentliche Deck.</em>', aiText: 'JustFlip enthält KI-gestützte Workflows, die Notizen, Artikel, Bücher, Vorlesungen und Ideen in importierbare Karteikarten verwandeln. Beginne mit einem kuratierten Deck, wenn es passt. Danach erstellst du dein eigenes.', aiCta: 'Eigenes Deck erstellen', libraryEyebrow: 'Kuratierte Sammlung', libraryTitle: 'Etwas, das es wert ist,<br><em>behalten zu werden.</em>', libraryText: 'Lade ein Deck herunter, öffne es in JustFlip und beginne mit dem Lernen. Jedes Deck ist in den unterstützten App-Sprachen verfügbar.', all: 'Alle Decks', languages: 'Sprachen', music: 'Musik', mathematics: 'Mathematik', programming: 'Programmierung', science: 'Naturwissenschaften', download: 'Deck laden', cards: 'Karten', pack: 'Paket', packs: 'Pakete', finalEyebrow: 'Bring deine Neugier mit', finalTitle: 'Das beste Deck ist das,<br><em>das du heute brauchst.</em>', finalText: 'Beginne mit einem kuratierten Deck, importiere aus Anki oder erstelle mit KI-gestützten Workflows etwas ganz Eigenes — mit JustFlips ruhiger Lernroutine.', appStore: 'Im App Store laden' },
    es: { eyebrow: 'Una pequeña biblioteca para empezar', title: 'Empieza con un mazo.<br><em>Hazlo tuyo.</em>', lede: 'Explora mazos seleccionados de idiomas, música, matemáticas, programación y ciencia. Son un buen punto de partida, pero lo mejor es crear un mazo exactamente para lo que quieres recordar.', aiEyebrow: 'Un punto de partida mejor', aiTitle: 'Tu material es el <em>mazo de verdad.</em>', aiText: 'JustFlip incluye flujos de trabajo con IA para convertir apuntes, artículos, libros, clases e ideas en tarjetas importables. Empieza con un mazo seleccionado cuando te sirva. Después crea uno propio.', aiCta: 'Crear tu propio mazo', libraryEyebrow: 'Colección seleccionada', libraryTitle: 'Algo que merece la pena<br><em>recordar.</em>', libraryText: 'Descarga un mazo, ábrelo en JustFlip y empieza a repasar. Todos los mazos están disponibles en los idiomas compatibles de la app.', all: 'Todos los mazos', languages: 'Idiomas', music: 'Música', mathematics: 'Matemáticas', programming: 'Programación', science: 'Ciencia', download: 'Descargar mazo', cards: 'tarjetas', pack: 'paquete', packs: 'paquetes', finalEyebrow: 'Trae tu propia curiosidad', finalTitle: 'El mejor mazo es el que<br><em>necesitas hoy.</em>', finalText: 'Empieza con un mazo seleccionado, importa desde Anki o crea algo completamente tuyo con flujos de IA y el ritmo de repaso tranquilo de JustFlip.', appStore: 'Descargar en el App Store' },
    fr: { eyebrow: 'Une petite bibliothèque pour commencer', title: 'Commencez avec un paquet.<br><em>Faites-le vôtre.</em>', lede: 'Explorez des paquets sélectionnés pour les langues, la musique, les mathématiques, la programmation et les sciences. Ils constituent un bon point de départ — mais le vrai intérêt est de créer un paquet pour ce que vous voulez précisément retenir.', aiEyebrow: 'Un meilleur point de départ', aiTitle: 'Votre contenu est le <em>vrai paquet.</em>', aiText: 'JustFlip propose des flux de travail assistés par l’IA pour transformer notes, articles, livres, cours et idées en cartes importables. Commencez avec un paquet sélectionné quand c’est utile, puis créez le vôtre.', aiCta: 'Créer votre paquet', libraryEyebrow: 'Collection sélectionnée', libraryTitle: 'Quelque chose qui mérite<br><em>d’être retenu.</em>', libraryText: 'Téléchargez un paquet, ouvrez-le dans JustFlip et commencez vos révisions. Tous les paquets sont disponibles dans les langues prises en charge par l’app.', all: 'Tous les paquets', languages: 'Langues', music: 'Musique', mathematics: 'Mathématiques', programming: 'Programmation', science: 'Sciences', download: 'Télécharger', cards: 'cartes', pack: 'paquet', packs: 'paquets', finalEyebrow: 'Apportez votre curiosité', finalTitle: 'Le meilleur paquet est celui<br><em>dont vous avez besoin aujourd’hui.</em>', finalText: 'Commencez avec un paquet sélectionné, importez depuis Anki ou créez quelque chose qui vous ressemble avec l’IA et le rythme de révision serein de JustFlip.', appStore: 'Télécharger sur l’App Store' },
    it: { eyebrow: 'Una piccola raccolta per iniziare', title: 'Inizia con un mazzo.<br><em>Fallo tuo.</em>', lede: 'Esplora mazzi curati per lingue, musica, matematica, programmazione e scienze. Sono un buon punto di partenza — ma il vero valore è creare un mazzo esattamente per ciò che vuoi ricordare.', aiEyebrow: 'Un punto di partenza migliore', aiTitle: 'Il tuo materiale è il <em>vero mazzo.</em>', aiText: 'JustFlip include flussi di lavoro assistiti dall’IA per trasformare appunti, articoli, libri, lezioni e idee in schede importabili. Inizia da un mazzo curato quando ti serve, poi creane uno tuo.', aiCta: 'Crea il tuo mazzo', libraryEyebrow: 'Raccolta curata', libraryTitle: 'Qualcosa che vale la pena<br><em>ricordare.</em>', libraryText: 'Scarica un mazzo, aprilo in JustFlip e inizia a ripassare. Ogni mazzo è disponibile nelle lingue supportate dall’app.', all: 'Tutti i mazzi', languages: 'Lingue', music: 'Musica', mathematics: 'Matematica', programming: 'Programmazione', science: 'Scienze', download: 'Scarica mazzo', cards: 'schede', pack: 'mazzo', packs: 'mazzi', finalEyebrow: 'Porta la tua curiosità', finalTitle: 'Il mazzo migliore è quello<br><em>di cui hai bisogno oggi.</em>', finalText: 'Inizia da un mazzo curato, importa da Anki o crea qualcosa di completamente tuo con l’IA e il ritmo di ripasso tranquillo di JustFlip.', appStore: 'Scarica dall’App Store' },
    'pt-br': { eyebrow: 'Uma pequena biblioteca para começar', title: 'Comece com um deck.<br><em>Faça dele o seu.</em>', lede: 'Explore decks selecionados de idiomas, música, matemática, programação e ciências. Eles são um bom ponto de partida — mas o melhor é criar um deck exatamente para o que você quer lembrar.', aiEyebrow: 'Um ponto de partida melhor', aiTitle: 'O seu material é o <em>deck de verdade.</em>', aiText: 'O JustFlip inclui fluxos de trabalho com IA para transformar anotações, artigos, livros, aulas e ideias em cartões importáveis. Comece com um deck selecionado quando for útil. Depois, crie o seu.', aiCta: 'Criar seu próprio deck', libraryEyebrow: 'Coleção selecionada', libraryTitle: 'Algo que vale a pena<br><em>lembrar.</em>', libraryText: 'Baixe um deck, abra-o no JustFlip e comece a revisar. Todos os decks estão disponíveis nos idiomas compatíveis com o app.', all: 'Todos os decks', languages: 'Idiomas', music: 'Música', mathematics: 'Matemática', programming: 'Programação', science: 'Ciências', download: 'Baixar deck', cards: 'cartões', pack: 'pacote', packs: 'pacotes', finalEyebrow: 'Traga a sua curiosidade', finalTitle: 'O melhor deck é aquele de que<br><em>você precisa hoje.</em>', finalText: 'Comece com um deck selecionado, importe do Anki ou crie algo totalmente seu com fluxos de IA e o ritmo calmo de revisão do JustFlip.', appStore: 'Baixar na App Store' },
    ja: { eyebrow: 'まずは小さなライブラリから', title: 'デッキから始めよう。<br><em>自分のものにしよう。</em>', lede: '言語、音楽、数学、プログラミング、科学の厳選デッキを見てみましょう。学習の出発点として役立ちますが、本当の魅力は、覚えたいことに合わせてデッキを自分で作れることです。', aiEyebrow: 'もっと良い始め方', aiTitle: 'あなたの教材が、<em>本当のデッキ。</em>', aiText: 'JustFlipには、ノート、記事、本、講義、アイデアをインポート可能なフラッシュカードに変えるAI支援ツールが含まれています。必要なら厳選デッキから始め、次に自分だけのデッキを作りましょう。', aiCta: '自分のデッキを作る', libraryEyebrow: '厳選コレクション', libraryTitle: '覚えておきたい<br><em>何か。</em>', libraryText: 'デッキをダウンロードしてJustFlipで開き、復習を始めましょう。すべてのデッキはアプリの対応言語で利用できます。', all: 'すべてのデッキ', languages: '言語', music: '音楽', mathematics: '数学', programming: 'プログラミング', science: '科学', download: 'デッキをダウンロード', cards: 'カード', pack: 'パック', packs: 'パック', finalEyebrow: '好奇心を持ち込もう', finalTitle: '最高のデッキは、<br><em>今日必要なもの。</em>', finalText: '厳選デッキから始めることも、Ankiからインポートすることも、AI支援ツールとJustFlipの落ち着いた復習エンジンで自分だけのデッキを作ることもできます。', appStore: 'App Storeからダウンロード' },
    ko: { eyebrow: '작게 시작하는 라이브러리', title: '덱으로 시작하세요.<br><em>나만의 것으로 만드세요.</em>', lede: '언어, 음악, 수학, 프로그래밍, 과학을 위한 엄선된 덱을 살펴보세요. 좋은 출발점이지만, 진짜 매력은 기억하고 싶은 내용에 맞춰 직접 덱을 만드는 데 있습니다.', aiEyebrow: '더 나은 시작점', aiTitle: '당신의 자료가 <em>진짜 덱입니다.</em>', aiText: 'JustFlip에는 노트, 기사, 책, 강의, 아이디어를 가져올 수 있는 플래시카드로 바꾸는 AI 지원 도구가 포함되어 있습니다. 엄선된 덱으로 시작한 뒤 나만의 덱을 만들어 보세요.', aiCta: '나만의 덱 만들기', libraryEyebrow: '엄선된 컬렉션', libraryTitle: '기억할 가치가 있는<br><em>무언가.</em>', libraryText: '덱을 다운로드해 JustFlip에서 열고 복습을 시작하세요. 모든 덱은 앱이 지원하는 언어로 제공됩니다.', all: '모든 덱', languages: '언어', music: '음악', mathematics: '수학', programming: '프로그래밍', science: '과학', download: '덱 다운로드', cards: '카드', pack: '팩', packs: '팩', finalEyebrow: '호기심을 가져오세요', finalTitle: '최고의 덱은 오늘<br><em>필요한 덱입니다.</em>', finalText: '엄선된 덱으로 시작하거나 Anki에서 가져오거나, AI 지원 워크플로와 JustFlip의 차분한 복습 엔진으로 완전히 나만의 덱을 만들어 보세요.', appStore: 'App Store에서 다운로드' }
  };

  const fallbackDecks = [
    ['japanese-kana', 'Japanese', 'languages', 'rose'], ['mathematics-formulas', 'Mathematics', 'mathematics', 'blue'], ['music-chord-structure', 'Chord Structure by Intervals', 'music', 'gold'], ['music-key-signatures-major', 'Key Signatures — Major', 'music', 'gold'], ['music-key-signatures-minor', 'Key Signatures — Minor', 'music', 'gold'], ['music-notes-bass', 'Notes on the Staff — Bass', 'music', 'gold'], ['music-notes-treble', 'Notes on the Staff — Treble', 'music', 'gold'], ['kotlin-fundamentals', 'Kotlin', 'programming', 'violet'], ['swift-language-fundamentals', 'Swift', 'programming', 'orange'], ['swiftui-fundamentals', 'SwiftUI', 'programming', 'cyan'], ['electronics-fundamentals', 'Electronics', 'science', 'green']
  ].map(([slug, title, category, tone]) => ({ slug, title, category, tone, cards: 0, packs: 0, capabilities: [], description: '', file: `${title}.flashcards`, locale: 'en' }));

  const deckLabels = { en: 'Decks', cs: 'Balíčky', de: 'Decks', es: 'Mazos', fr: 'Paquets', it: 'Mazzi', 'pt-br': 'Decks', ja: 'デッキ', ko: '덱' };
  const t = (key) => key === 'decksLabel' ? (deckLabels[document.documentElement.lang] || deckLabels.en) : ((copy[document.documentElement.lang] || copy.en)[key] || copy.en[key]);
  const localisedFile = (entry) => {
    if (!entry.file) return '#';
    const name = entry.file.split('/').pop();
    const suffix = name.endsWith('.flashcards.zip') ? '.flashcards.zip' : '.flashcards';
    return `files/${entry.locale}/${encodeURIComponent(name.slice(0, -suffix.length) + ' (' + entry.locale + ')' + suffix)}`;
  };
  const icon = (category) => category === 'music' ? '♫' : category === 'programming' ? '&lt;/&gt;' : category === 'languages' ? 'あ' : category === 'mathematics' ? '∑' : category === 'science' ? '⌁' : '✦';
  const grid = document.getElementById('deck-grid');
  let catalog = window.JUSTFLIP_CATALOG?.decks || [];
  let decks = catalog.length
    ? catalog.filter((entry) => entry.locale === 'en').map((entry) => ({ ...entry, tone: fallbackDecks.find((deck) => deck.slug === entry.slug).tone }))
    : fallbackDecks;
  let filter = 'all';

  function updateCopy() {
    document.querySelectorAll('[data-decks-key]').forEach((el) => { el.innerHTML = t(el.dataset.decksKey); });
    document.querySelectorAll('.decks-filter').forEach((el) => { el.textContent = t(el.dataset.decksKey); });
  }

  function render() {
    const lang = document.documentElement.lang || 'en';
    const visible = decks.filter((deck) => filter === 'all' || deck.category === filter);
    const labels = { languages: t('languages'), music: t('music'), mathematics: t('mathematics'), programming: t('programming'), science: t('science') };
    grid.innerHTML = visible.map((deck, index) => {
      const entry = deck.locale === lang ? deck : (catalog.find((candidate) => candidate.slug === deck.slug && candidate.locale === lang) || deck);
      const count = entry.cards || deck.cards;
      const packs = entry.packs || deck.packs;
      return `<article class="deck-tile deck-tile--${deck.tone}" style="--tile-index:${index}" tabindex="0"><div class="deck-tile__top"><span class="deck-tile__category">${labels[deck.category]}</span><span class="deck-tile__number">${String(index + 1).padStart(2, '0')}</span></div><div class="deck-tile__glyph" aria-hidden="true">${icon(deck.category)}</div><h3>${entry.title || deck.title}</h3><p>${entry.description || deck.description}</p><div class="deck-tile__foot"><span>${count} ${t('cards')} · ${packs} ${packs === 1 ? t('pack') : t('packs')}</span><span class="deck-tile__capabilities">${(entry.capabilities || []).join(' · ')}</span><a href="${localisedFile(entry)}" download>${t('download')} <span aria-hidden="true">↗</span></a></div></article>`;
    }).join('');
  }

  document.querySelectorAll('.decks-filter').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.decks-filter').forEach((item) => item.classList.remove('is-active')); button.classList.add('is-active'); filter = button.dataset.filter; render(); }));
  grid.addEventListener('click', (event) => { const tile = event.target.closest('.deck-tile'); if (tile && !event.target.closest('a')) tile.querySelector('a[download]')?.click(); });
  grid.addEventListener('keydown', (event) => { if ((event.key === 'Enter' || event.key === ' ') && event.target.closest('.deck-tile') && !event.target.closest('a')) { event.preventDefault(); event.target.closest('.deck-tile').querySelector('a[download]')?.click(); } });
  updateCopy();
  render();
  new MutationObserver(() => { updateCopy(); render(); }).observe(document.documentElement, { attributes: true, attributeFilter: ['lang'] });
  if (!catalog.length) fetch('catalog.json').then((response) => response.json()).then((data) => { catalog = data.decks; decks = catalog.filter((entry) => entry.locale === 'en').map((entry) => ({ ...entry, tone: fallbackDecks.find((deck) => deck.slug === entry.slug).tone })); render(); }).catch(() => {});
})();
